all: difference_and_sum

difference_and_sum: difference_and_sum.c difference_and_sum.h
	gcc -Wall -ansi -pedantic -g -o difference_and_sum difference_and_sum.c

# Rule to easily remove compiled files
clean:
	rm -f difference_and_sum